"""Fetch the MJX scene XMLs and meshes needed by the offline MPC examples.

Asset directories live under ``tests/mpc_examples/data/`` and are
``.gitignore``-d (the repo only tracks ``data/.gitignore`` itself), so a
fresh clone has no robot meshes. Run this script once before invoking the
MPC examples or smoke tests.

Source preference:

1. If the env var ``MPX_LOCAL_PATH`` points to a local ``mpx`` checkout,
   copy from ``$MPX_LOCAL_PATH/mpx/data/{aliengo,unitree_h1}``.
2. Else, download from the pinned mpx commit (see ``MPX_COMMIT``) on
   ``raw.githubusercontent.com``.

Every fetched file is verified against a known SHA-256 in
``KNOWN_SHA256``. Mismatches abort the fetch — protects against silent
upstream tampering, force-pushed branches, in-flight corruption, or a
drifted local mpx checkout. Bumping ``MPX_COMMIT`` requires regenerating
the hashes (see ``--regenerate-hashes``).

By default fetches both robot families. Use ``--robots aliengo`` (or
``unitree_h1``) to pull just one. Re-running is idempotent — existing
files are skipped (and re-verified) unless ``--force`` is passed.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import shutil
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path

DATA_DIR = Path(__file__).resolve().parent / "data"

# Pinned to a specific mpx commit so the files we fetch are immutable
# (a SHA can't be force-pushed away from without re-creating the same
# bits, and even then KNOWN_SHA256 below would catch the mismatch).
MPX_COMMIT = "6f830d2140af550af6e8e65b18ade2d1d056584b"
GITHUB_BASE = f"https://raw.githubusercontent.com/iit-DLSLab/mpx/{MPX_COMMIT}/mpx/data/"

# Files we actually need. Limited to: scene XML + included sub-XML +
# every file under assets/ (textures + meshes).
ALIENGO_FILES = [
    "aliengo/scene_flat.xml",
    "aliengo/aliengo.xml",
    *[
        f"aliengo/assets/{name}"
        for name in (
            "calf.stl",
            "hip.stl",
            "thigh_mirror.stl",
            "thigh.stl",
            "trunk.stl",
        )
    ],
]

UNITREE_H1_FILES = [
    "unitree_h1/mjx_scene_h1_walk.xml",
    "unitree_h1/mjx_h1_walk_real_feet.xml",
    *[
        f"unitree_h1/assets/{name}"
        for name in (
            "left_ankle_link.stl",
            "left_elbow_link.stl",
            "left_hip_pitch_link.stl",
            "left_hip_roll_link.stl",
            "left_hip_yaw_link.stl",
            "left_knee_link.stl",
            "left_shoulder_pitch_link.stl",
            "left_shoulder_roll_link.stl",
            "left_shoulder_yaw_link.stl",
            "logo_link.stl",
            "pelvis.stl",
            "right_ankle_link.stl",
            "right_elbow_link.stl",
            "right_hip_pitch_link.stl",
            "right_hip_roll_link.stl",
            "right_hip_yaw_link.stl",
            "right_knee_link.stl",
            "right_shoulder_pitch_link.stl",
            "right_shoulder_roll_link.stl",
            "right_shoulder_yaw_link.stl",
            "torso_link.stl",
        )
    ],
]

# SHA-256 of every file we fetch, captured at MPX_COMMIT. Generated by
# `python -m tests.mpc_examples.fetch_assets --regenerate-hashes` after
# bumping MPX_COMMIT.
KNOWN_SHA256 = {
    "aliengo/scene_flat.xml": "b8a817f3ff2421f8d22a8142740e8f625ddf2fc2590f0651f02721aad638d973",
    "aliengo/aliengo.xml": "9c53670283a81a898b550db26dcf9204c8881dd19e22e2967130238209253e7d",
    "aliengo/assets/calf.stl": "bbb56eb25e4171e1d5e0120481644e8a6e3406feb91ac02521dc1bb54888af80",
    "aliengo/assets/hip.stl": "865a5af12717fa64e722e0f75787dcadbde140ee9d91cae1a00d2f382be2bf48",
    "aliengo/assets/thigh_mirror.stl": "e504a94860925b2dcb98289fa9eb7edcc31c14d4c7902446478453de7e1c32bd",
    "aliengo/assets/thigh.stl": "9a8e1c7a54fb43015d6c24ef90c0dba9086dead0f3950daac3e62edfbd3f2279",
    "aliengo/assets/trunk.stl": "7914b93b9f7af9aaa0eadc480894ca716b172ce2b7b184187a66339aaa401f6a",
    "unitree_h1/mjx_scene_h1_walk.xml": "0a1d21236985412652952e423b9ca19d7cd8f98664abfb4728742cfbb66baeb7",
    "unitree_h1/mjx_h1_walk_real_feet.xml": "ab933d7fff3bb6820a69e5ed56cce2b066d60bfcd90002e632b0e40d6a898f18",
    "unitree_h1/assets/left_ankle_link.stl": "f623223b59d0f8cd86a799f409f4e8680da3e48d9b60e9f4bf9dad5c5dc8ac25",
    "unitree_h1/assets/left_elbow_link.stl": "5ccf9bc83a751c1965b692e75534e57ee3c8a0916cbcff2ccccd8fe2b9d818d7",
    "unitree_h1/assets/left_hip_pitch_link.stl": "aa790c31ffc100cd182f2bf4480e7bfda675edc58ed8f361b6553a4975c9de3b",
    "unitree_h1/assets/left_hip_roll_link.stl": "8ed880cf1171e048cfe50489fe2546c32790ac0c24a2b3b4c560495401013552",
    "unitree_h1/assets/left_hip_yaw_link.stl": "103a854e684b84e1baba7d073822079069c64d0fa7b1592f29d38bd29f545bfb",
    "unitree_h1/assets/left_knee_link.stl": "efda8a6c54406c788102c0d6e59ea95e24114607bc2da9a2bf7f287ef7e48109",
    "unitree_h1/assets/left_shoulder_pitch_link.stl": "42e1db49464ca0f44f933114ee426e7f6d6310d20cf104bfa38b5ed4794cfab7",
    "unitree_h1/assets/left_shoulder_roll_link.stl": "8d3bcf767d72a9a5d7dae539eae79dc4132f0159b8803a6f6f2f9ad4b7e94d19",
    "unitree_h1/assets/left_shoulder_yaw_link.stl": "e22a5b53f8f307e6c5d6c17f9ceae4852c6468547a951cb39dfdec9ee414b515",
    "unitree_h1/assets/logo_link.stl": "ef9635c847ca7cd61aeaed86ad599935b648fb6f8688867c0448917b1811511b",
    "unitree_h1/assets/pelvis.stl": "dc2cbbeb07d3b63bce9fedeb8cf5252609dca1e89380734d22d5b3c8ded2f15c",
    "unitree_h1/assets/right_ankle_link.stl": "a72e7b10d3961b5c5bb7b0ca09f20cbc203619f5ded33ca030517c06298d2fd9",
    "unitree_h1/assets/right_elbow_link.stl": "bc1b2aa33cffda279b3e6a40b5b932b86de9cce6c41f0c0d860b442e81edcdc2",
    "unitree_h1/assets/right_hip_pitch_link.stl": "3c0300dd96432f218857886007e9d4e8be038cd8b85e04e84a59df4de7f90476",
    "unitree_h1/assets/right_hip_roll_link.stl": "3e95b01b0a215e1d134545d4073cf7a72ab38ca33e35c606c03f1706d63588c6",
    "unitree_h1/assets/right_hip_yaw_link.stl": "10badbb0ac78e22fc220f421b1c919cfcf59406b412d78313e4b8b06cbc51e47",
    "unitree_h1/assets/right_knee_link.stl": "6183abbaef2afc775c220853e403b8479022a99954dbeef829b39d71916ddeda",
    "unitree_h1/assets/right_shoulder_pitch_link.stl": "850ffa7321993bfadcdb8bab1d422239f6a20abe27daa5ef99622f55d4da3217",
    "unitree_h1/assets/right_shoulder_roll_link.stl": "b9e793e351e09027d27427c06df2c1cb6b37c0205d0f68686b0d73916c6821de",
    "unitree_h1/assets/right_shoulder_yaw_link.stl": "0c9e4bec895f24c07fb2c4d132fc5e3cc7146155547267e9c270789af6567781",
    "unitree_h1/assets/torso_link.stl": "3ab785cbfbd851b0e9c59a46871aabc4718f3f8e726e21a2d14360d217ec7ba8",
}


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _local_source_root() -> Path | None:
    env = os.environ.get("MPX_LOCAL_PATH")
    if env:
        candidate = Path(env).expanduser() / "mpx" / "data"
        if candidate.is_dir():
            return candidate
    return None


def _verify(rel_path: str, dest: Path) -> None:
    """Hash dest, error out if it doesn't match KNOWN_SHA256[rel_path]."""
    expected = KNOWN_SHA256.get(rel_path)
    if expected is None:
        msg = f"No known SHA-256 for {rel_path}; refusing to install unverified file"
        raise RuntimeError(msg)
    actual = _sha256_file(dest)
    if actual != expected:
        # Remove the unverified file so a re-run can attempt again.
        dest.unlink(missing_ok=True)
        msg = (
            f"SHA-256 mismatch for {rel_path}\n"
            f"  expected: {expected}\n"
            f"  actual:   {actual}\n"
            f"This may indicate upstream tampering, a force-pushed mpx commit, "
            f"in-flight corruption, or a drifted local mpx checkout."
        )
        raise RuntimeError(msg)


def _fetch_one(rel_path: str, source: Path | None, force: bool) -> bool:
    """Return True if file was actually fetched, False if it was already present + verified."""
    dest = DATA_DIR / rel_path
    if dest.exists() and not force:
        # Re-verify in case the on-disk file rotted somehow.
        _verify(rel_path, dest)
        return False
    dest.parent.mkdir(parents=True, exist_ok=True)
    if source is not None:
        src = source / rel_path
        if not src.exists():
            msg = f"{rel_path} not present in local mpx checkout at {source}"
            raise RuntimeError(msg)
        shutil.copyfile(src, dest)
    else:
        _download(GITHUB_BASE + rel_path, dest)
    _verify(rel_path, dest)
    return True


def _download(url: str, dest: Path) -> None:
    """Try urllib first, fall back to curl on SSL/network failure.

    Python's ssl module enforces RFC 5280 strictly in 3.13+ (e.g.
    rejects CA certs with non-critical Basic Constraints), and the
    image's CA bundle often doesn't include corporate roots used by
    TLS-intercepting proxies (Zscaler etc.). curl is typically more
    lenient and uses the system trust store directly, so it succeeds
    in environments where urllib chokes. Both succeed for everyone
    else, in which case the fallback never fires.
    """
    urllib_err = None
    try:
        with urllib.request.urlopen(url) as resp, open(dest, "wb") as f:
            shutil.copyfileobj(resp, f)
        return
    except (urllib.error.URLError, OSError) as e:
        urllib_err = e
    try:
        subprocess.run(
            ["curl", "-fsSL", "-o", str(dest), url],
            check=True,
            capture_output=True,
            text=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError) as curl_err:
        msg = f"Failed to download {url}\n  urllib: {urllib_err}\n  curl:   {curl_err}"
        raise RuntimeError(msg) from curl_err


def fetch(robots: list[str], force: bool = False) -> None:
    source = _local_source_root()
    if source is not None:
        print(f"Copying assets from local mpx: {source}")
    else:
        print(f"Downloading assets from GitHub @ {MPX_COMMIT[:8]}")

    plans = {"aliengo": ALIENGO_FILES, "unitree_h1": UNITREE_H1_FILES}
    for robot in robots:
        files = plans[robot]
        print(f"\n[{robot}] {len(files)} files")
        fetched = 0
        for rel in files:
            if _fetch_one(rel, source, force):
                fetched += 1
        print(
            f"[{robot}] fetched {fetched}, skipped {len(files) - fetched} (all SHA-256 verified)"
        )


def regenerate_hashes() -> None:
    """Print a fresh KNOWN_SHA256 dict from the local mpx checkout.

    Intended workflow when bumping ``MPX_COMMIT``:
      1. cd to your mpx clone, ``git checkout <new-sha>``.
      2. Run ``MPX_LOCAL_PATH=… python -m tests.mpc_examples.fetch_assets --regenerate-hashes``.
      3. Paste the printed dict into ``KNOWN_SHA256`` and update
         ``MPX_COMMIT`` in this file.
    """
    source = _local_source_root()
    if source is None:
        msg = (
            "MPX_LOCAL_PATH must point at the parent of your mpx checkout to "
            "regenerate hashes (we read from disk to avoid bootstrapping issues)."
        )
        raise RuntimeError(msg)
    print("KNOWN_SHA256 = {")
    for rel in (*ALIENGO_FILES, *UNITREE_H1_FILES):
        path = source / rel
        if not path.exists():
            print(f"    # MISSING: {rel}", file=sys.stderr)
            continue
        print(f'    "{rel}": "{_sha256_file(path)}",')
    print("}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument(
        "--robots",
        nargs="+",
        choices=["aliengo", "unitree_h1"],
        default=["aliengo", "unitree_h1"],
    )
    parser.add_argument("--force", action="store_true", help="re-fetch even if present")
    parser.add_argument(
        "--regenerate-hashes",
        action="store_true",
        help="Print a fresh KNOWN_SHA256 dict from $MPX_LOCAL_PATH and exit. "
        "Use after bumping MPX_COMMIT.",
    )
    args = parser.parse_args()
    if args.regenerate_hashes:
        regenerate_hashes()
        return
    fetch(args.robots, force=args.force)


if __name__ == "__main__":
    main()
